WebAppCarsLobby/Controllers/CarsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppCarsLobby.Models.Cars;

namespace WebAppCarsLobby.Controllers
{
    public class CarsController : Controller
    {
        ICarService _carService;

        public CarsController()
        {
            _carService = new CarService();
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_carService.GetCars());
        }

        [HttpGet]
        public IActionResult Create()
        {
            CreateCarViewModel createCar = new CreateCarViewModel();
            createCar.BrandList = _carService.Getbrands();

            return View(createCar);
        }

        [HttpPost]
        public IActionResult Create(CreateCarViewModel createCar)
        {
            if (ModelState.IsValid)
            {
                _carService.CreateCar(createCar);
                return RedirectToAction("Index");
            }

            createCar.BrandList = _carService.Getbrands();

            return View(createCar);
        }
    }
}

WebAppCarsLobby/Controllers/ColorTheSiteController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppCarsLobby.Controllers
{

    public class ColorTheSiteController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            string cookieColor = Request.Cookies["cookieColor"];

            if (cookieColor != null)
            {
                ViewBag.CookieColor = cookieColor;
            }

            return View();
        }

        [HttpPost]
        public IActionResult SetColor(int id)
        {
            //Add cookie to Response object
            CookieOptions option = new CookieOptions();
            option.Expires = DateTime.Now.AddMinutes(1);

            switch (id)
            {
                case 1:
                    Response.Cookies.Append("cookieColor", "blackPage", option);
                    break;
                case 2:
                    Response.Cookies.Append("cookieColor", "whitePage", option);
                    break;
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

WebAppCarsLobby/Controllers/ToDoItController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppCarsLobby.Controllers
{
    public class ToDoItController : Controller
    {
        [HttpGet]
        public IActionResult Memo()
        {
            string memos = HttpContext.Session.GetString("Memos");
            if (memos != null)
            {
                ViewBag.Memos = memos;
            }
            return View();
        }

        [HttpPost]
        public IActionResult AddMemo(string memo)
        {
            if ( ! string.IsNullOrWhiteSpace(memo))
            {
                string memos = HttpContext.Session.GetString("Memos");
                if (memos == null)
                {
                    HttpContext.Session.SetString("Memos", memo);
                }
                else
                {
                    memos += '|' + memo;
                    HttpContext.Session.SetString("Memos", memos);
                }
            }

            return RedirectToAction(nameof(Memo));
            //return View("Memo");
        }
    }
}

WebAppCarsLobby/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/Site.css" rel="stylesheet" asp-append-version="true" />
</head>
<body class="@ViewBag.CookieColor">
    <header>
        <h3>Logo</h3>
        <nav>
            <ul>
                <li>
                    <a asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li>
                    <a asp-controller="Cars" asp-action="Index">Cars</a>
                </li>
                <li>
                    <a asp-controller="ToDoIt" asp-action="Memo">ToDo It</a>
                </li>
                <li>
                    <a asp-controller="ColorTheSite" asp-action="Index">Cookie Color</a>
                </li>
            </ul>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
    <footer>
        <p>&copy; Ulf B.</p>
    </footer>
</body>
</html>